name: Weekly Build

# 触发器
on:
  schedule:
    - cron: '0 15 * * 0' #每周天在国际标准时间15点(北京时间+8，即 23:00)
  workflow_dispatch:
    inputs:
      root_sol:
        description: "Weekly Build Title"
        required: true
        default: "SmsForwarder"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v2
      # 删除旧的工作流
      - name: Delete Weekly Build
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0 # 全部删除只留正在跑的一条
          keep_minimum_runs: 0 # 全部删除只留正在跑的一条
          delete_workflow_pattern: 'Weekly Build'
      # 设置jdk环境为11
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # 获取打包秘钥
      - name: Checkout Android Keystore
        uses: actions/checkout@v2
        with:
          repository: pppscn/keystore
          token: ${{ secrets.TOKEN }} # 连接仓库的token,需要单独配置
          path: keystore # 仓库的根目录名
      # 打包release
      - name: Build with Gradle
        run: bash ./gradlew assembleRelease
      # 生成文件列表并上传 Artifacts
      - name: Upload Artifacts
        run: |
          # 使用 find 命令生成文件列表
          artifact_files=$(find build/app/outputs/apk/release -name "*.apk")
          
          # 输出找到的文件列表
          echo "Found APK files: $artifact_files"
          
          # 将文件列表写入文件
          echo "$artifact_files" > artifact_files.txt
          
          # 逐个上传文件至 Artifacts
          for file in $artifact_files; do
            artifact_name=$(basename "$file")  # 获取文件名（不包含路径）
            echo "Uploading $file to Artifacts with name $artifact_name"
            echo "$file" >> $GITHUB_ENV  # 将每个文件路径追加到环境变量文件
          done
        shell: bash
      # 上传 Artifacts，使用真实文件名作为 Artifacts 名称（不包含路径）
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAMES }}  # 使用不带路径的文件名
          path: artifact_files.txt  # 使用保存文件路径的文件
          if-no-files-found: error
